### ISSUE TITLE
help with running the app

### ISSUE THREAD

**Issue by mmeeeooowww** [wickeyware/wickeyappstore#1]
Hi I'm trying to start the app via:
`npm install`
`npm run start`

but i get teh following error

```
ERROR in src\app\app.module.ts(17,5): Error during template compile of 'AppModule'
  Could not resolve wickeyappstore relative to C:/projects/wickeyappstore-1.16.1/src/app/app.module.ts..
src/app/app.component.ts(2,61): error TS2307: Cannot find module 'wickeyappstore'.
src/app/app.module.ts(4,38): error TS2307: Cannot find module 'wickeyappstore'.
```

any ideas on what I could be doing wrong?

**Comment by wickeym** [comment]
Hi,

You need to first install the WAS lib locally (I forgot to update the README).
`npm run build:lib`

The test project uses it, which is the error you are seeing.

Sincerely,
Michael
